[[plugins]]
repo = 'nakatakeshi/show_github_url.vim'

[[plugins]]
repo = 'gosukiwi/vim-atom-dark'

[[plugins]]
repo = 'Shougo/denite.nvim'

[[plugins]]
repo = 'Shougo/neomru.vim'

[[plugins]]
repo = 'Shougo/neoyank.vim'

[[plugins]]
repo = 'tomasr/molokai'

[[plugins]]
repo = 'elixir-editors/vim-elixir'

[[plugins]]
repo = 'mhinz/vim-mix-format'

[[plugins]]
repo = 'tomtom/tcomment_vim'

[[plugins]]
repo = 'kassio/neoterm'

[[plugins]]
repo = 'slashmili/alchemist.vim'

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'leafgarland/typescript-vim'

[[plugins]]
repo = 'nelstrom/vim-visual-star-search'

[[plugins]]
repo = 'fatih/vim-go'

[[plugins]]
repo = 'prabirshrestha/async.vim'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'prabirshrestha/asyncomplete.vim'

[[plugins]]
repo = 'prabirshrestha/asyncomplete-lsp.vim'

[[plugins]]
repo = 'junegunn/vim-easy-align'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'tyru/operator-camelize.vim'

[[plugins]]
repo = 'ryanolsonx/vim-lsp-python'
on_ft = ['python']
depends = ['vim-lsp']

[[plugins]]
repo = 'ConradIrwin/vim-bracketed-paste'

[[plugins]]
repo = 'kana/vim-textobj-user'

[[plugins]]
repo = 'mattn/vim-goimports'

[[plugins]]
repo = 'junegunn/fzf'
build_on = '''
./install -all
'''

[[plugins]]
repo = 'junegunn/fzf.vim'

[[plugins]]
repo = 'skanehira/preview-markdown.vim'

[[plugins]]
repo = 'rust-lang/rust.vim'

[[plugins]]
repo = 'mattn/vim-lsp-settings'

[[plugins]]
repo = 'editorconfig/editorconfig-vim'

[[plugins]]
repo = 'tsandall/vim-rego'

